command:
  - python
  - app.py

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: SERVING_ENDPOINT_NAME
    valueFrom: serving-endpoint

permissions:
  - permission: CAN_QUERY
    resource_type: serving-endpoint
    resource_name: agents_aia_multi_agent_catalog-ai_ops-supervisor_agent
  - permission: CAN_USE
    resource_type: sql-warehouse
    resource_name: sql-warehouse
